token:
  experation_time: 86400000
  secret: '{cipher}AQAytGzgLWhjgmrystel2M6u3sVAXbi4mPkdYWK6mufK+4z9/QOKaeAUbgfYYpG6tZFdPN3GrpmQe5aJ5IHZ62lsJ4SNHYRAtG5KSjwvFs8BetpcWIr7M9q4XxTMIlAxpxwfIIXYiAxvp+4ic962ywPicgvTs5o1mH54NwGhnlmYn2cRwa+SRnJzF3FT4U8jrf5h/dxQXqJBXf+Xh24iVCjY47Hye+a3h7nKvNuexJ96BPFqODKQ1sUJnknGkVxLvAw2A/Zc0K41p1wpIliKSha6f3UEjn4ldFPRCWRJDV/BWwzq7C5JkTzRvZZJq1BqutzCkno8/0mz6OEyhhEAGDOH5UcatxUeiiN0UapdWFFx7m4WTcCamawjph7IJvQ3+FZfFEjNQYM8pDXRD4Gwu5yd'

greeting:
  message: Welcomt to the Simple E-commerce

kafka:
  ipv4_address: 127.0.0.1:9092

gateway:
#  ip: 10.11.6.5
  ip: 172.18.0.9  # Docker ApiGateway-service 의 ip
