spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: '{cipher}AQCI9UOqd6at9z8GMrdGrgHtOvy164D2xgP/N49gsKCcPGYD1mKe4Ebs+4waao4mFEFCJf01kJyOEpNZo67BB2NUulTpxosaQEQbgwm6iLUkonTNBLjhD3T2UOiHOPQVn7ORJWbHRMTCt48Acj69wuH0UCAf+JBq+7bbi9pp42ZFsnhb2rYQjFfGDcP9Mq0I6/RiBkC02v62qrEw1XexigfCtxZYxq8fAFz9BPpeEv0D7gmUwsDPlpYe5nu0QE+G7sjOyYQpHSnVgSveKcqovzX6m/ieoQRVugvG5K8/op4uk1RjTRJCIEaJmXlzKghjbrEdDP7k1aV5geb2uhFWa5/xjHMTJZHnSt5P925v92gq+mIgwN7h3TCQxYsqUAZGL0k='
gateway:
#  ip: 10.11.6.5
  ip: 172.18.0.5  # Docker 용도
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: There is no item.

